version: 1
profile:
    email: hacepif560@docsfy.com
    accountId: 712020:107429f8-e69a-4e7f-875c-eb34df930fd1
    auth_type: api_token
    token: !!binary |
        8OOTLCc5IFzQIfJbsv5qK4QjtfYV8v0c75kornyc9UM6OjphZDFkYzJhYjJhYTcyMDMxMz
        FkMTEyYTQ0M2VmNjAzNGU1ZDkxMTkxYTdhZGYxYWE5YTA2MzM4ZmVhZDY5OWNlZWMwZGIz
        MzVmM2Q3NWFhOTg0ZTdlZWMxNTBkN2U3NTJjYTZkYTViNjI1MzY5YmRjOTk5MmQxMTI2Mj
        FiMzg1ZjZmM2U1ZTA1ODNkZjhiYmI5NGMzZjYzOGUyMjhiMzZiNWYxM2QwNDUyNWE4MjFh
        NWY3YzE4ZmUyMDJjNzIzN2ExOTFhMDY4MTc1NGU4YzhlOTlmOTg1MzFlYzkzZDhhMTFiNG
        FhMDQwNWNlNzhmMjQzZDkyOThiMTNkNjE2NTBkYjI3ZjhmYTZiODdhOTFhNWFiY2Q2OGIz
        Mzk0YWYyM2E5YTY3MWM1MDA5ODY4MTQzY2ZjMWE5ZjliNWI1MjFkYjhlMjNkZWE4MDEwYW
        U2NzBjNTFmZTlkOGRhNjYyMTY0ZGU1MzM2NDRjMTVkZjBhN2QwMzg2MDBlZWUxZjA1YmRl
        ODEzMTVmZDE2ODI5NjI5NzJjOWZkY2VkMjk0NzQ4YTFlMTIxMWVmOTMzNWM3MWM3YmQxMz
        hjMA==
